use crate::commands::{Context, normalize_subdir};
use crate::git_utils::{run_git, try_run_git};
use anyhow::Result;

pub fn run(subdir: String, key: String, value: Option<String>, force: bool) -> Result<()> {
    let ctx = Context::new()?;

    let subdir = normalize_subdir(&subdir);
    let gitrepo_path = ctx.repo_root.join(&subdir).join(".gitrepo");
    let gitrepo_path_str = gitrepo_path.to_string_lossy().into_owned();

    let valid_keys = ["branch", "cmdver", "commit", "method", "remote", "version"];
    if !valid_keys.contains(&key.as_str()) {
        anyhow::bail!("Option {key} not recognized");
    }

    let config_key = format!("subrepo.{key}");

    if value.is_none() {
        // Read mode
        let (ok, out) = try_run_git(
            &["config", "--file", &gitrepo_path_str, &config_key],
            &ctx.repo_root,
        );
        if ok {
            println!("Subrepo '{subdir}' option '{key}' has value '{out}'.");
        } else {
            anyhow::bail!("Failed to read config key '{key}'");
        }
        return Ok(());
    }

    let val = value.unwrap();

    // Write mode - needs force for most keys
    if !force && key != "method" {
        anyhow::bail!("This option is autogenerated, use '--force' to override.");
    }

    if key == "method" && val != "merge" && val != "rebase" {
        anyhow::bail!("Not a valid method. Valid options are 'merge' or 'rebase'.");
    }

    run_git(
        &["config", "--file", &gitrepo_path_str, &config_key, &val],
        &ctx.repo_root,
    )?;

    println!("Subrepo '{subdir}' option '{key}' set to '{val}'.");

    Ok(())
}
