#![allow(dead_code)]

use thiserror::Error;

#[derive(Debug, Error)]
pub enum SubrepoError {
    #[error("{0}")]
    Git(#[from] git2::Error),

    #[error("{0}")]
    Io(#[from] std::io::Error),

    #[error("You can't clone into an empty repository")]
    EmptyRepo,

    #[error("Not inside a git repository.")]
    NotInRepo,

    #[error("Must be on a branch to run this command.")]
    NotOnBranch,

    #[error("Need to run subrepo command from top level directory of the repo.")]
    NotTopLevel,

    #[error("Can't {0} subrepo. Unstaged changes. ({1})")]
    UnstagedChanges(String, String),

    #[error("Can't {0} subrepo. Working tree has changes. ({1})")]
    WorkingTreeDirty(String, String),

    #[error("Can't {0} subrepo. Index has changes. ({1})")]
    IndexDirty(String, String),

    #[error("Can't determine subdir from '{0}'.")]
    CantGuessSubdir(String),

    #[error("Can't fetch subrepo. Remote is 'none' in '{0}/.gitrepo'.")]
    RemoteIsNone(String),

    #[error("There are new changes upstream, you need to pull first.")]
    NeedPullFirst,

    #[error("No subrepo branch '{0}' to push.")]
    NoBranchToPush(String),

    #[error("Can't commit: '{0}' doesn't contain upstream HEAD.")]
    CommitMissingUpstreamHead(String),

    #[error("Branch '{0}' already exists. Use '--force' to override.")]
    BranchExists(String),

    #[error("There is no worktree available, use the branch command first")]
    NoWorktree,

    #[error(
        "There is already a worktree with branch subrepo/{0}.\nUse the --force flag to override this check or perform a subrepo clean\nto remove the worktree."
    )]
    WorktreeExists(String),

    #[error("Can't find ref '{0}'. Try using -F.")]
    RefNotFound(String),

    #[error("Option {0} not recognized")]
    UnknownConfigOption(String),

    #[error("Not a valid method. Valid options are 'merge' or 'rebase'.")]
    InvalidMethod,

    #[error("This option is autogenerated, use '--force' to override.")]
    AutogeneratedOption,

    #[error("Can't '{0}' while subrepo branch is checked out.")]
    SubrepoBranchCheckedOut(String),

    #[error(
        "The last sync point (where upstream and the subrepo were equal) is not an ancestor. \n \
            This is usually caused by a rebase affecting that commit. \n \
            To recover set the subrepo parent in '{0}'\n \
            to '{1}' \n \
            and validate the subrepo by comparing with 'git subrepo branch {2}'"
    )]
    SyncPointNotAncestor(String, String, String),

    #[error(
        "Local repository does not contain {0}. Try to 'git subrepo fetch {1}' or add the '-F' flag to always fetch the latest content."
    )]
    CommitNotLocal(String, String),

    #[error("Problem finding remote default head branch.")]
    NoDefaultBranch,

    #[error("The subdir '{0}' exists and is not empty.")]
    SubdirNotEmpty(String),

    #[error("The subdir '{0}' does not exist.")]
    SubdirNotExist(String),

    #[error("The subdir '{0}' is already a subrepo.")]
    AlreadySubrepo(String),

    #[error("The subdir '{0}' is not part of this repo.")]
    SubdirNotInRepo(String),

    #[error("{0}")]
    General(String),
}

impl SubrepoError {
    pub fn general(msg: impl Into<String>) -> Self {
        SubrepoError::General(msg.into())
    }
}

pub type SubrepoResult<T> = Result<T, SubrepoError>;
